smallkinejobs/application

app/imports/ui/layouts/App.jsx, app/imports/ui/pages/Landing.jsx
Resolves #21 
From landing page enter job title you want to search then click search button which will go to job search results page with the passed query
=> connect landing page search to results page

app/imports/ui/components/Skills.jsx, app/imports/ui/pages/DisplayProfile.jsx, app/package-lock.json, app/package.json
I added a section for recommended jobs based on skill matches between employee profiles and skills listed  for a job. Also added open modal functionality akin to the functionality found on the JobSearchResults page to allow a user to click on and apply to jobs that are listed as recommended on their Profile.
resolves #24
=> Fleshed Out Profile Page With Recommended Jobs

app/imports/ui/pages/Landing.jsx
Think I forgot to add the landing page code. Should of checked the revisions. Its added now though.
=> fix the missing code

app/imports/ui/pages/Landing.jsx
The landing page search functionality should be working now. I also fixed some of the eslint errors in the Landing page file. Please check the diffs and make sure this PR won't break anything.
resolves #32
=> Fixed Landing Page Search Functionality

app/client/main.html, app/imports/ui/layouts/App.jsx, app/imports/ui/pages/DisplayProfile.jsx, app/imports/ui/pages/EditResume.jsx
add resume page for user
resolves #31
=> add resume page

app/imports/ui/layouts/App.jsx, app/imports/ui/pages/SigninSKJ.jsx
need to mess around with alignment of UH login button
resolves #4
=> sign page not search page mock up, nearly done

app/imports/api/jobs/index.js, app/imports/api/jobs/jobs.js, app/imports/startup/both/index.js, app/imports/startup/server/index.js, app/imports/startup/server/jobs.js, app/imports/ui/pages/JobSearchResult.jsx, config/settings.development.json
I implemented the Jobs Mongo collection, added publishing code to the server side, and had the JobSearchResults page subscribe to this collection. I also added default jobs data to the settings.development.json file for testing. The only issue is figuring out a clean way to ensure that the subscription to the collection will be ready immediately prior to rendering the page, so that the job results can be displayed. Right now, this is being done via a `getJobs()` method that is called at the top of the `renderPage()` method if `this.state.jobs` is an empty array.
resolves #18
=> Implementation of the Jobs Mongo Collection

app/imports/api/categories/categories.js, app/imports/api/categories/index.js, app/imports/startup/both/index.js, app/imports/startup/server/categories.js, app/imports/startup/server/index.js, config/settings.development.json
I have implemented the Job Categories collection, added some default categories to the settings.development.json file, and added publishing code to the server side. The code is pretty minimal now. Any pages that are related to adding/opening jobs in the system should subscribe to the Categories collection.
resolves #46
=> Implementation of the Job Categories Collection

app/imports/api/jobs/jobs.js, app/imports/startup/server/jobs.js, app/imports/ui/components/EmployeeLanding.jsx, app/imports/ui/components/EmployerLanding.jsx, app/imports/ui/components/JobCard.jsx, app/imports/ui/components/NavBar.jsx, app/imports/ui/pages/JobSearchResult.jsx, app/imports/ui/pages/Landing.jsx, config/settings.development.json
Split the landing page based on roles and move the search bar to the navbar.
=> Job search result

app/imports/api/skills/index.js, app/imports/api/skills/skills.js, app/imports/startup/both/index.js, app/imports/startup/server/index.js, app/imports/startup/server/skills.js, config/settings.development.json
Added in the MongoDB collection for handling Skills, as well as some defaultSkills for testing.
resolves #45
=> Implementation of Skills Collection

app/imports/ui/components/BaseLanding.jsx, app/imports/ui/pages/Landing.jsx, app/imports/ui/pages/SignupEmployee.jsx
should have fixed the issue with the landing page
=> changed the sign up button no console errors on landing page

app/imports/startup/server/accounts.js, app/imports/ui/pages/Landing.jsx
Fixed how the server did adding roles of default users.
Changed Landing so that it now checks the user's actual roles for which page to load.
=> fix server default roles and proper landing handling

app/imports/ui/components/EmployeeJobCard.jsx, app/imports/ui/components/EmployeeLanding.jsx, app/imports/ui/components/EmployerJobCard.jsx, app/imports/ui/components/EmployerLanding.jsx, app/imports/ui/components/JobSearchCard.jsx, app/imports/ui/pages/DisplayProfile.jsx, app/imports/ui/pages/JobSearchResult.jsx, app/imports/ui/pages/Landing.jsx
Fixed from merges for the job skills to now show in job cards.
Also JobCard got split into EmployerJobCard and EmployeeJobCard
Resolves #68
=> fixed the missing skills

app/imports/ui/components/EmployeeJobCard.jsx, app/imports/ui/components/EmployerJobCard.jsx, app/imports/ui/components/JobSearchCard.jsx, config/settings.development.json
=> Fix default data

app/imports/api/jobs/jobs.js, app/imports/ui/components/EmployeeJobCard.jsx, app/imports/ui/components/EmployeeLanding.jsx, app/imports/ui/components/EmployerJobCard.jsx, app/imports/ui/components/EmployerLanding.jsx, config/settings.development.json
Each users can now rate each other and the card will respond accordingly. Employer will rate employee and their view of the card will be closed. Employee will still have a Completed job card status until they submit a rating.
=> fix both job cards for feedbacks

app/imports/ui/components/EmployeeJobCard.jsx, app/imports/ui/components/EmployeeLanding.jsx, config/settings.development.json
I have added in the ability for an employee user to mark their in progress jobs as completed, to signify that they have completed the job. 
resolves #53
=> Added Employee Mark job as Completed Functionality

app/imports/startup/server/accounts.js, app/imports/startup/server/jobs.js, app/imports/startup/server/ratings.js, app/imports/ui/components/EmployeeCard.jsx, app/imports/ui/components/EmployerLanding.jsx
=> Modify Employee Cards to display past helpers taken from Jobs collection

app/imports/ui/components/EmployeeJobCard.jsx, app/imports/ui/components/EmployeeLanding.jsx, app/imports/ui/components/EmployerJobCard.jsx, app/imports/ui/components/JobDetailModal.jsx, app/imports/ui/components/JobSearchCard.jsx, config/settings.development.json
=> Fix job detail modal

app/imports/ui/components/EmployeeCard.jsx, app/imports/ui/components/EmployerJobCard.jsx, app/imports/ui/components/EmployerLanding.jsx, app/imports/ui/components/HireHelperModal.jsx, config/settings.development.json
=> Data job applicants

app/imports/ui/components/EmployerLanding.jsx
I fixed the bug on the Employer Landing page where the same previous helper was being rendered in an EmployeeCard multiple times.
Resolves #93
=> Fixed duplicate past helpers bug

app/imports/ui/components/EmployeeLanding.jsx, app/imports/ui/components/JobDetailModal.jsx, config/settings.development.json
=> disable apply button if already applied

app/imports/ui/components/EmployerLanding.jsx
=> change userId to username when submitting job

app/imports/ui/components/EmployeeLanding.jsx
=> fix employee showing proper job cards

app/imports/ui/pages/JobSearchResult.jsx
=> add job filter on mount and look for open == 1
